### ISSUE TITLE
parsing fails when extra symbols are in the ppen file.

### ISSUE THREAD

**Issue by iainwp** [tdobra/tctemplate#3]
If I've got this right then there is a bug when additional symbols are added to a `ppen` file.  Attached are two `ppen` files `withbug` and `withoutbug`.  The difference is simply a text label (`V1`), which I was using to mark the viewing point in the all controls map.  It doesn't appear in the other maps.  The presence this item seems to be causing the parsing of the `ppen` file to fail when it's loaded.  

The map file is included too, for convenience, but doesn't affect the bug.

[for-td.zip](https://github.com/tdobra/tctemplate/files/4480363/for-td.zip)

**Comment by tdobra** [comment]
Resolved by ignoring <course> elements in Purple Pen file that do not have a child <name> element. See commits e253752 and ab7c7c8.
